name: Octopoes Run the robot framework integration tests

on:
  push:
    branches:
      - "main"
      - "release-*"
    tags:
      - "*"
    paths:
      - octopoes/**
      - .github/workflows/octopoes_rtest.yml
  pull_request:
    paths:
      - octopoes/**
      - .github/workflows/octopoes_rtest.yml

jobs:
  rtest:
    permissions:
      contents: read
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
          cache: "pip" # caching pip dependencies

      - name: Install requirements-dev.txt
        run: pip install -r requirements-dev.txt
        working-directory: ./octopoes

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0
        id: buildx

      - name: Run robot tests
        run: make rtest
        env:
          DOCKER_BUILDKIT: 1
        working-directory: ./octopoes
